### ISSUE TITLE
dparse 0.4.0 breaks safety

### ISSUE THREAD

**Issue by rlupton20** [pyupio/safety#122]
* safety version: 1.8.0
* Python version: 3.6
* Operating System: Container build (debian python container)

### Description

`safety check` no longer runs. Suspect breaking API change in new version of `dparse`.

### What I Did

Clean install of safety, followed by `safety check`. Produces stack trace:

```
$ safety check
Traceback (most recent call last):
  File "/usr/local/bin/safety", line 7, in <module>
    from safety.cli import cli
  File "/usr/local/lib/python3.6/site-packages/safety/cli.py", line 9, in <module>
    from safety.util import read_requirements
  File "/usr/local/lib/python3.6/site-packages/safety/util.py", line 1, in <module>
    from dparse.parser import setuptools_parse_requirements_backport as _parse_requirements
  File "/usr/local/lib/python3.6/site-packages/dparse/__init__.py", line 9, in <module>
    from .parser import parse
  File "/usr/local/lib/python3.6/site-packages/dparse/parser.py", line 31, in <module>
    from .vendor import toml
ModuleNotFoundError: No module named 'dparse.vendor'
```

Seems to have occurred on dependency being resolved from dparse version 0.3.0 to 0.4.0.

**Comment by jayfk** [comment]
Yup, dparse `0.4.0` has a packaging error. `0.4.1` is currently being pushed to PyPi. Once that's complete, I'm going to issue a new Safety release `1.8.1`.

**Comment by rlupton20** [comment]
Thanks - I'm pinning the `dparse` version for now.

**Comment by jayfk** [comment]
`1.8.1` is now available on PyPi :)

**Comment by rlupton20** [comment]
Thanks, can confirm this is working.
