### ISSUE TITLE
Recursive requirements crashing from stdin

### ISSUE THREAD

**Issue by g-k** [pyupio/safety#128]
* safety version: 1.8.1
* Python version: 3.5.5
* Operating System: ubuntu 16.04 (via the ubuntu:16.04 docker image) (also for OSX 10.13.4 (17E199))

### Description

Run safety on a requirements file with [a recursive requirement](https://pip.readthedocs.io/en/1.1/requirements.html#recursive-requirements) from `--stdin` e.g. `-r requirements.txt` from `requirements-dev.txt`

what happened/what went wrong: safety crashed
what you expected to happen: safety not to crash and check the remaining lines. Logging a warning to stderr would be good too.

### What I Did

```
wget https://raw.githubusercontent.com/mozilla/pontoon/6fe02c4734d6f60df45dd2f829cfdc3d40faa9b6/requirements-dev.txt

If there was a crash, please include the traceback here.

Traceback (most recent call last):
  File "/usr/local/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/safety/cli.py", line 63, in check
    vulns = safety.check(packages=packages, key=key, db_mirror=db, cached=cache, ignore_ids=ignore)
  File "/usr/local/lib/python3.5/dist-packages/safety/safety.py", line 133, in check
    name = pkg.key.replace("_", "-").lower()
AttributeError: 'RequirementFile' object has no attribute 'key'
```

**Comment by g-k** [comment]
Use case is checking many repos without cloning them.

**Comment by rafaelpivato** [comment]
I'm wondering what would be the fallback decision? Should we look into current working directory for the included file named `requirements.txt`? Or should we just ignore and warn about those when we are reading from stdin?

**Comment by rafaelpivato** [comment]
Just for the records, a nice-to-have feature would be supporting HTTP URLs right away, and be able to perform such relative references.
