### ISSUE TITLE
Support for URLs in input requirements.txt files

### ISSUE THREAD

**Issue by Lucas-C** [pyupio/safety#18]
Hi,

This is a feature request.

Lets start by stating that, following the spec, URLs to tarballs are part of the requirements file format
https://pip.readthedocs.io/en/1.1/requirements.html#requirements-file-format

Now, the `pkg_resources.parse_requirements` function used by `safety` does not support them:
https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L2850
It raises a `RequirementParseError: Invalid requirement, parse error`.

I had a look at how they handle this in `pip`, and it's ugly:
https://github.com/pypa/pip/blob/master/pip/req/req_set.py#L690

`pip-tools` does not support them. It actually crashes in a bad way if you try so: https://github.com/nvie/pip-tools/issues/416

By the way, URLs to tarball specified as editable requirements (with `-e`) work fine: curiously `pkg_resources.parse_requirements` handle them perfectly well.

What do you think ? Should `safety` handle them ?

**Comment by jayfk** [comment]
`safety` just needs:
 - a package name 
 - the exact version that is going to be installed

It's possible to add the package name to the URL via `#egg=`. 

What about the version? If there is a reliable way to get it, `safety` should probably support that.

**Comment by jayfk** [comment]
In all cases, `safety` shouldn't fail with an error.

**Comment by Lucas-C** [comment]
I just did a quick test and adding the `#egg=` URL suffix does not help:
```
from pkg_resources import parse_requirements
list(parse_requirements('https://files.pythonhosted.org/packages/6a/11/114c67b0e3c25c19497fde977538339530d8ffa050d6ec9349793f933faa/lockfile-0.10.2.tar.gz#egg=lockfile==0.10.2')
RequirementParseError: Invalid requirement, parse error at "'://files'"
```

**Comment by jayfk** [comment]
Yeah, that doesn't work.

I should've made this clearer in my previous comment: `safety` should support every input as long as it's possible to parse the exact version and the package name. 

Currently it only supports the requirements.txt syntaxt with `package-name==version`.

**Comment by ye** [comment]
I agree with @Lucas-C that `safety` should support pip requirements file format fully to include URL to tarballs/compressed archives like what @jayfk mentioned with the help of `#egg` URL anchor to indicate a package name and exact version. At the very minimum, `safety` should NOT spit out stack trace when it sees URLs in the pip file or any invalid pip package entries.

One of the use case for me is to be able to install the latest but unreleased code from a package with arbitrary version pinning. For instance, this `safety` check fails currently.

```bash
$ mkvirtualenv temp
$ pip install https://github.com/pyupio/safety/archive/master.zip#egg=safety-0.5.2
Collecting safety-0.5.2 from https://github.com/pyupio/safety/archive/master.zip#egg=safety-0.5.2
  Downloading https://github.com/pyupio/safety/archive/master.zip
  Running setup.py (path:/private/var/folders/y2/8qncmkqn4xzb0l6m2fjdbsy80000gn/T/pip-build-9_2f64lh/safety-0.5.2/setup.py) egg_info for package safety-0.5.2 produced metadata for project name safety. Fix your #egg=safety-0.5.2 fragments.
Requirement already satisfied: Click>=6.0 in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: requests in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: packaging in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: setuptools>=16 in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: six in /Users/ye/.envs/temp/lib/python3.5/site-packages (from packaging->safety)
Requirement already satisfied: pyparsing in /Users/ye/.envs/temp/lib/python3.5/site-packages (from packaging->safety)
Requirement already satisfied: appdirs>=1.4.0 in /Users/ye/.envs/temp/lib/python3.5/site-packages (from setuptools>=16->safety)
Installing collected packages: safety
  Running setup.py install for safety ... done
Successfully installed safety-0.5.1

(temp) $ safety check -r requirements.txt 
Traceback (most recent call last):
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2890, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'://githu'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ye/.envs/temp/bin/safety", line 11, in <module>
    load_entry_point('safety==0.5.1', 'console_scripts', 'safety')()
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/safety/cli.py", line 79, in check
    vulns = safety.check(packages=packages)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/safety/safety.py", line 34, in check
    for pkg in packages:
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/safety/cli.py", line 46, in read_requirements
    for req in parse_requirements("\n".join(reqs)):
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2883, in parse_requirements
    yield Requirement(line)
  File "/Users/ye/.envs/temp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2892, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'://githu'"
```

Note that which version to pin down in `#egg` anchor is debatable, but at least it provides all required information for `safety` to perform safety check against the vulnerability db. 

#38 is also related and should be covered as a part of this ticket.

**Comment by ye** [comment]
It appears that safety check after package installed could be a workaround for now. That is, the `pip freeze | safety check --stdin` approach works as pip freeze outputs package names and versions regardless what package sources are specified in the `requirements.txt`.

**Comment by jayfk** [comment]
I'm going to work on this today. Do you have additional files/requirements that are not working to date?

I'd like to build up a strong testcase to support most of them.

**Comment by jayfk** [comment]
Okay, most of this should work thanks to https://github.com/pyupio/safety/commit/f51f05b08842c9ce4322d05d644500dbb8458673.

Could you update and try again?

**Comment by ye** [comment]
@jayfk yup, the latest master works great with the HTTP url.

```bash
$ pip install https://github.com/pyupio/safety/archive/master.zip#egg=safety-0.6.0
Collecting safety-0.6.0 from https://github.com/pyupio/safety/archive/master.zip#egg=safety-0.6.0
  Downloading https://github.com/pyupio/safety/archive/master.zip
     \ 20kB 1.4MB/s
  Running setup.py (path:/private/var/folders/y2/8qncmkqn4xzb0l6m2fjdbsy80000gn/T/pip-build-ji4va6cf/safety-0.6.0/setup.py) egg_info for package safety-0.6.0 produced metadata for project name safety. Fix your #egg=safety-0.6.0 fragments.
Requirement already satisfied: Click>=6.0 in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: requests in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: packaging in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: setuptools>=16 in /Users/ye/.envs/temp/lib/python3.5/site-packages (from safety)
Requirement already satisfied: six in /Users/ye/.envs/temp/lib/python3.5/site-packages (from packaging->safety)
Requirement already satisfied: pyparsing in /Users/ye/.envs/temp/lib/python3.5/site-packages (from packaging->safety)
Requirement already satisfied: appdirs>=1.4.0 in /Users/ye/.envs/temp/lib/python3.5/site-packages (from setuptools>=16->safety)
Installing collected packages: safety
  Running setup.py install for safety ... done
Successfully installed safety-0.6.0

$ cat test-requirements.txt 
https://github.com/pyupio/safety/archive/master.zip#egg=safety-0.6.0

$ safety check -r test-requirements.txt 
Warning: unpinned requirement 'safety-0.6.0' found, unable to check.
╒══════════════════════════════════════════════════════════════════════════════╕
│                                                                              │
│                               /$$$$$$            /$$                         │
│                              /$$__  $$          | $$                         │
│           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           │
│          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           │
│         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           │
│          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           │
│          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           │
│         |_______/  \_______/|__/     \_______/   \___/   \____  $$           │
│                                                          /$$  | $$           │
│                                                         |  $$$$$$/           │
│  by pyup.io                                              \______/            │
│                                                                              │
╞══════════════════════════════════════════════════════════════════════════════╡
│ REPORT                                                                       │
╞══════════════════════════════════════════════════════════════════════════════╡
│ No known security vulnerabilities found.                                     │
╘══════════════════════════════════════════════════════════════════════════════╛
```

One tiny caveat is that it didn't recognize the `#egg=` part to extract version info (hence the unpinned requirement warning).

**Comment by jayfk** [comment]
That's because `safety-0.6.0` isn't a valid specifier. Using `safety==0.6.0` should work.

**Comment by ye** [comment]
Ok, so no way to extract version info from a HTTP pip package source?

**Comment by jayfk** [comment]
Of course!

Instead of

```
https://github.com/pyupio/safety/archive/master.zip#egg=safety-0.6.0
```

you use

```
https://github.com/pyupio/safety/archive/master.zip#egg=safety==0.6.0
```

**Comment by ye** [comment]
Ok thanks, that worked albeit it feels a little awkward and different from [PIP's VCS support syntax](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)...but I will take it!

**Comment by jayfk** [comment]
The problem is that you need to actually execute a package's `setup.py` to get the version that's going to be installed via VCS. This basically means to install the package.

That's something I really don't want to do. It's unexpected from a user POV and has side effects.
