### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ktosiek** [pyupio/safety#22]
* safety version: 0.5.1
* Python version: 2.7.6
* Operating System: Ubuntu 14.04 LTS

### Description

Full report with non-ascii data causes UnicodeEncodeError

### What I Did

```
$ echo 'cryptography==1.3.2' | safety check --stdin --full-report
Traceback (most recent call last):
  File "/home/tkontusz/.local/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/safety/cli.py", line 80, in check
    click.secho(report(vulns=vulns, full=full_report))
  File "/home/tkontusz/.local/venvs/safety/local/lib/python2.7/site-packages/safety/formatter.py", line 62, in report
    table.append("│ {:76} │".format(line))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 22: ordinal not in range(128)

```

**Comment by maratsh** [comment]
I have same error.

**Comment by jayvdb** [comment]
https://github.com/pyupio/safety/pull/36 should fix this.
