### ISSUE TITLE
dparse-0.5 is broken on Python 2

### ISSUE THREAD

**Issue by lanzz** [pyupio/safety#296]
* safety version: 1.8.7
* Python version: 2.7.15
* Operating System: macOS, Ubuntu

### Description

`safety` has a dependency on `dparse>=0.4.1`, but on 2020/03/14 `dparse` released version 0.5 that only supports Python 3.x, but does _not_ have a `python_requires = '>=3.0'` constraint in its `setup.py`, so `pip` will happily install v0.5 in Python 2 environments.

`dparse-0.5` will assume anything that's not a `str` to be a nested iterable to process recursively, but `safety` passes requirements lines to `setuptools_parse_requirements_backport` as `unicode` instances, so `dparse` tries to recursively parse the first character of the line forever, eventually exceeding the maximum stack depth.

Issue in `dparse`'s tracker: https://github.com/pyupio/dparse/issues/46

### What I Did

```bash
$ safety check --full-report -r output_of_pip_freeze.txt
Traceback (most recent call last):
  File "/Users/lanzz/.pyenv/versions/2.7.15/bin/safety", line 10, in <module>
    sys.exit(cli())
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/safety/cli.py", line 59, in check
    packages = list(itertools.chain.from_iterable(read_requirements(f, resolve=True) for f in files))
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/safety/util.py", line 80, in read_requirements
    req, = parse_line(parseable_line)
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/dparse/parser.py", line 62, in setuptools_parse_requirements_backport
    for line in lines:
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/dparse/parser.py", line 58, in yield_lines
    for s in yield_lines(ss):
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/dparse/parser.py", line 58, in yield_lines
    for s in yield_lines(ss):
  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/dparse/parser.py", line 58, in yield_lines
    for s in yield_lines(ss):

. . . skip lots of repeats from the same line 58 . . .

  File "/Users/lanzz/.pyenv/versions/2.7.15/lib/python2.7/site-packages/dparse/parser.py", line 50, in yield_lines
    if isinstance(strs, str):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by rafaelpivato** [comment]
Python version was dropped with version 0.5 you can still use 0.4 anyway. There is a bug anyway with the published package that does not includes `py_requires` attribute.

**Comment by rafaelpivato** [comment]
We are open to consider whether Python 2.7 support should be back to master branch. At this moment, if you depend on Python 2.7 you should be able to use dparse version 0.4.
