### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by kulapard** [pyupio/safety#44]
* safety version: 1.0.0
* Python version: 2.7.13
* Operating System: macOS 10.12.3

### Description

Installed fresh safety and run `safety check`.
Got `NameError: global name 'FileNotFoundError' is not defined` error.

### What I Did

```
(hic) ➜  HiConversion pip install -U safety
Collecting safety
  Downloading safety-1.0.0-py2.py3-none-any.whl
Requirement already up-to-date: packaging in /Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages (from safety)
Collecting requests (from safety)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting setuptools>=16 (from safety)
  Using cached setuptools-34.3.2-py2.py3-none-any.whl
Requirement already up-to-date: Click>=6.0 in /Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages (from safety)
Requirement already up-to-date: six in /Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages (from packaging->safety)
Collecting pyparsing (from packaging->safety)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools>=16->safety)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Installing collected packages: requests, appdirs, setuptools, safety, pyparsing
  Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
  Found existing installation: appdirs 1.4.0
    Uninstalling appdirs-1.4.0:
      Successfully uninstalled appdirs-1.4.0
  Found existing installation: setuptools 34.2.0
    Uninstalling setuptools-34.2.0:
      Successfully uninstalled setuptools-34.2.0
  Found existing installation: safety 0.6.0
    Uninstalling safety-0.6.0:
      Successfully uninstalled safety-0.6.0
  Found existing installation: pyparsing 2.1.10
    Uninstalling pyparsing-2.1.10:
      Successfully uninstalled pyparsing-2.1.10
Successfully installed appdirs-1.4.3 pyparsing-2.2.0 requests-2.13.0 safety-1.0.0 setuptools-34.3.2
(hic) ➜  HiConversion safety check
class _(tuple):
    '_(rows,)'

    __slots__ = ()

    _fields = ('rows',)

    def __new__(_cls, rows,):
        'Create new instance of _(rows,)'
        return _tuple.__new__(_cls, (rows,))

    @classmethod
    def _make(cls, iterable, new=tuple.__new__, len=len):
        'Make a new _ object from a sequence or iterable'
        result = new(cls, iterable)
        if len(result) != 1:
            raise TypeError('Expected 1 arguments, got %d' % len(result))
        return result

    def __repr__(self):
        'Return a nicely formatted representation string'
        return '_(rows=%r)' % self

    def _asdict(self):
        'Return a new OrderedDict which maps field names to their values'
        return OrderedDict(zip(self._fields, self))

    def _replace(_self, **kwds):
        'Return a new _ object replacing specified fields with new values'
        result = _self._make(map(kwds.pop, ('rows',), _self))
        if kwds:
            raise ValueError('Got unexpected field names: %r' % kwds.keys())
        return result

    def __getnewargs__(self):
        'Return self as a plain tuple.  Used by copy and pickle.'
        return tuple(self)

    __dict__ = _property(_asdict)

    def __getstate__(self):
        'Exclude the OrderedDict from pickling'
        pass

    rows = _property(_itemgetter(0), doc='Alias for field number 0')


Traceback (most recent call last):
  File "/Users/kulapard/virtualenvs/hic/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/safety/cli.py", line 41, in check
    click.secho(report(vulns=vulns, full=full_report))
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/safety/formatter.py", line 127, in report
    size = get_terminal_size()
  File "/Users/kulapard/virtualenvs/hic/lib/python2.7/site-packages/safety/formatter.py", line 14, in get_terminal_size
    except (ValueError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by jayfk** [comment]
Thanks for reporting, fixed in https://github.com/pyupio/safety/commit/10d606090eb13d373b8d16142284c302dd76780f and https://github.com/pyupio/safety/commit/ed15d7f100dcc3b7c62b4546e3f9e6ca49742c68
