### ISSUE TITLE
Unhandled exception happened: 'redis'

### ISSUE THREAD

**Issue by mgedmin** [pyupio/safety#471]
* safety version: 2.3.5
* Python version: 3.11
* Operating System: Debian 11

### Description

Our GitLab CI uses a 'python' Docker image to run safety checks, and these suddenly started failing with a mysterious "Unhandled exception happened: 'redis'" message.

```
$ pip3 install safety
...
Successfully installed Click-8.1.3 certifi-2022.12.7 charset-normalizer-3.1.0 dparse-0.6.2 idna-3.4 packaging-21.3 pyparsing-3.0.9 requests-2.28.2 ruamel.yaml-0.17.21 safety-2.3.5 toml-0.10.2 urllib3-1.26.15
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: pip install --upgrade pip
$ safety check -r server/requirements.txt --full-report
Unhandled exception happened: 'redis'
ERROR: Job failed: exit code 1
```

### What I Did

```
pip3 install safety
safety check -r server/requirements.txt --full-report
```

I'm unable to reproduce this issue locally, even when I use the same 'python' docker image.  Instead I get a proper report about a vulnerability in redis (vuln. id 53868).

**Comment by Corentin-Br** [comment]
It seems to be the `insecure_full.json` file that is not always correct.
On local and on CI, I manage to get both valid and invalid results with enough attempts.

**Comment by yeisonvargasf** [comment]
@mgedmin and @Corentin-Br, I'm trying to reproduce this issue; I'll be grateful if you can share an anonymized debug from the Safety execution. You can run it with the debug flag:

`safety --debug check`

**Comment by Darkborderman** [comment]
Hello @yeisonvargasf I encounter similar issue today.  The error context:
```
Unhandled exception happened: 'graphene-django'
```

And it looks like the JSON vulnerabilities differs sometimes when safety try to retrieve it

The result runs with `safety --debug check`
```
2023-05-31 13:28:00,930 safety.cli => Telemetry enabled: True
2023-05-31 13:28:00,931 safety.cli => Running check command
2023-05-31 13:28:01,089 safety.cli => Calling the check function
2023-05-31 13:28:01,100 safety.util => Telemetry body built: {'os_type': 'Darwin', 'os_release': '22.4.0', 'os_description': 'macOS-13.3.1-x86_64-i386-64bit', 'python_version': '3.8.13', 'safety_command': 'check', 'safety_options': {}, 'safety_version': '2.3.5', 'safety_source': 'cli'}
2023-05-31 13:28:01,108 urllib3.connectionpool => Starting new HTTPS connection (1): pyup.io:443
2023-05-31 13:28:01,158 urllib3.connectionpool => https://pyup.io:443 "GET /aws/safety/free/insecure.json?telemetry=%7B%22os_type%22%3A+%22Darwin%22%2C+%22os_release%22%3A+%2222.4.0%22%2C+%22os_description%22%3A+%22macOS-13.3.1-x86_64-i386-64bit%22%2C+%22python_version%22%3A+%223.8.13%22%2C+%22safety_command%22%3A+%22check%22%2C+%22safety_options%22%3A+%7B%7D%2C+%22safety_version%22%3A+%222.3.5%22%2C+%22safety_source%22%3A+%22cli%22%7D HTTP/1.1" 200 117782
2023-05-31 13:28:01,169 safety.util => Telemetry body built: {'os_type': 'Darwin', 'os_release': '22.4.0', 'os_description': 'macOS-13.3.1-x86_64-i386-64bit', 'python_version': '3.8.13', 'safety_command': 'check', 'safety_options': {}, 'safety_version': '2.3.5', 'safety_source': 'cli'}
2023-05-31 13:28:01,182 urllib3.connectionpool => https://pyup.io:443 "GET /aws/safety/free/insecure_full.json?telemetry=%7B%22os_type%22%3A+%22Darwin%22%2C+%22os_release%22%3A+%2222.4.0%22%2C+%22os_description%22%3A+%22macOS-13.3.1-x86_64-i386-64bit%22%2C+%22python_version%22%3A+%223.8.13%22%2C+%22safety_command%22%3A+%22check%22%2C+%22safety_options%22%3A+%7B%7D%2C+%22safety_version%22%3A+%222.3.5%22%2C+%22safety_source%22%3A+%22cli%22%7D HTTP/1.1" 200 3777902
2023-05-31 13:28:01,345 safety.cli => Unexpected Exception happened: 'graphene-django'
Traceback (most recent call last):
  File "/Users/darkborderman/.pyenv/versions/3.8.13/envs/Napoleon-3.8/lib/python3.8/site-packages/safety/cli.py", line 145, in check
    vulns, db_full = safety.check(packages=packages, key=key, db_mirror=db, cached=cache, ignore_vulns=ignore,
  File "/Users/darkborderman/.pyenv/versions/3.8.13/envs/Napoleon-3.8/lib/python3.8/site-packages/safety/util.py", line 614, in new_func
    return f(*args, **kwargs)
  File "/Users/darkborderman/.pyenv/versions/3.8.13/envs/Napoleon-3.8/lib/python3.8/site-packages/safety/safety.py", line 345, in check
    for data in get_vulnerabilities(pkg=name, spec=specifier, db=db_full):
  File "/Users/darkborderman/.pyenv/versions/3.8.13/envs/Napoleon-3.8/lib/python3.8/site-packages/safety/safety.py", line 231, in get_vulnerabilities
    for entry in db[pkg]:
KeyError: 'graphene-django'
Unhandled exception happened: 'graphene-django'
2023-05-31 13:28:01,346 safety.cli => Calling clean up on close function.
2023-05-31 13:28:01,346 safety.safety => Closing requests session.
```

**Comment by dylanpulver** [comment]
duplicate of https://github.com/pyupio/safety/issues/490
