### ISSUE TITLE
AttributeError: Requirement instance has no attribute 'name'

### ISSUE THREAD

**Issue by klada** [pyupio/safety#51]
* safety version: 1.1.1
* Python version: 2.7
* Operating System: RHEL7

### Description

Whenever **safety** stumbles over unpinned requirements, it fails with an exception:

This is the result:

```
Traceback (most recent call last):
  File "/opt/virtualenv/safety/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/safety/cli.py", line 40, in check
    vulns = safety.check(packages=packages, key=key, db_mirror=db, cached=cache)
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/safety/safety.py", line 130, in check
    for pkg in packages:
  File "/opt/virtualenv/safety/lib/python2.7/site-packages/safety/util.py", line 81, in read_requirements
    req=req.name),
AttributeError: Requirement instance has no attribute 'name'
```

This happens both with unpinned versions in `requirements.txt` and with unpinned versions in the `pip freeze` output (e.g. git snapshots).

In my setup the parsed requirement `req`, which is accessed on line 81 in `utils.py` only has the following attributes:

```
['specifier', 'project_name', 'unsafe_name', 'key', 'hashCmp', '_Requirement__hash', 'specs', 'extras']
```

It looks like you are trying to access the `name` attribute of a `Requirement`, which should not be present according to [setuptool's documentation](http://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirement-methods-and-attributes).

**Comment by jayfk** [comment]
Thanks for reporting!

Could you attach the output of `pip freeze` (maybe remove private packages)?

**Comment by klada** [comment]
It happens for example with this simple requirements.txt file:

```
Django>=1.10,<1.11
```

I have prepared a PR which resolves the issue for me.
