### ISSUE TITLE
Nested requirements.txt files are not processed

### ISSUE THREAD

**Issue by andrei-shabanski** [pyupio/safety#6]
* safety version:0.3.0
* Python version:3.5.1
* Operating System: Ubuntu 16.04

### Description

`safery` can't handle nested requirements.txt files.

### What I Did

Example, there are 3 files: main.txt, dev.txt, requirements.txt:

* main.txt

```
django==1.10.3
celery==3.1.23
```

* dev.txt

```
ipython==5.1.0
pytest==3.0.3
fake-factory=0.5.7
```

* requirements.txt

```
-r main.txt
-r dev.txt
```

Run safety:

```sh
$ cat requirements.txt | safety check --stdin

Traceback (most recent call last):
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2873, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-r main.'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/venvs/abcd-xyz/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/safety/cli.py", line 40, in check
    vulns = safety.check(packages=packages)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/safety/safety.py", line 54, in check
    for pkg in packages:
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/safety/cli.py", line 16, in read_requirements
    for req in parse_requirements(fh.read()):
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2866, in parse_requirements
    yield Requirement(line)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2875, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-r main.'"
```

**Comment by jayfk** [comment]
This should no longer throw an exception with `0.4.0`.

Resolving other requirement files is a bit tricky when reading from stdin. There's just no reliable way to tell where the referenced requirements files are.

They could be in the current working directory, but we can't be sure about that.

**Comment by jayfk** [comment]
That's now in `0.5.0`.

Running 
```
safety check -r requirements.txt
```
will now check a requirements file and resolve all referenced files.

People are pretty familiar with the `-r` option from pip, so I've used that here too. Optionally, it's also possible to use `--file`.
