### ISSUE TITLE
Handle packages which have been install from a variety of VCS

### ISSUE THREAD

**Issue by andrei-shabanski** [pyupio/safety#7]
safety version:0.3.0
Python version:3.5.1
Operating System: Ubuntu 16.04

### Description
  
`safery` can't handle `requirements.txt` with packages which have been installed from VCS directly.

### What I Did

requirements.txt:

```
-e git+https://github.com/django/django.git@802dd1ffc5cfa3d547efeb285dac70884b99e16d#egg=django
```

Run safety:

```
$ cat requirements.txt | safety check --stdin

Traceback (most recent call last):
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2873, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-e git+h'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/venvs/abcd-xyz/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/safety/cli.py", line 40, in check
    vulns = safety.check(packages=packages)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/safety/safety.py", line 54, in check
    for pkg in packages:
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/safety/cli.py", line 16, in read_requirements
    for req in parse_requirements(fh.read()):
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2866, in parse_requirements
    yield Requirement(line)
  File "/home/vagrant/venvs/abcd-xyz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2875, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-e git+h'"
```

**Comment by jayfk** [comment]
safety now filters out requirements that are installed directly from git.
