### ISSUE TITLE
AttributeError: 'Requirement' object has no attribute 'project_name' for VCS requirements

### ISSUE THREAD

**Issue by koniiiik** [pyupio/safety#72]
* safety version: 1.5.0
* Python version: 2.7.6
* Operating System: Ubuntu Trusty

### Description

$SUBJ when there's a git requirement, like for example this:
```
-e git+https://github.com/jdunck/python-unicodecsv#egg=unicodecsv
```

Here's the traceback:

```
$  safety check -r requirements.txt
Traceback (most recent call last):
  File "/home/vagrant/build/venv/bin/safety", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/safety/cli.py", line 55, in check
    vulns = safety.check(packages=packages, key=key, db_mirror=db, cached=cache, ignore_ids=ignore)
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/safety/safety.py", line 132, in check
    for pkg in packages:
  File "/home/vagrant/build/venv/local/lib/python2.7/site-packages/safety/util.py", line 81, in read_requirements
    req=req.project_name),
AttributeError: 'Requirement' object has no attribute 'project_name'
```

**Comment by jayfk** [comment]
Thanks for reporting. Fixed in https://github.com/pyupio/safety/commit/bf7cbd448d05a338d596c4eeb50ff0e324d74003

I've issued a new bugfix release: `1.5.1` should be available in a couple of minutes on PyPi. In the meantime, `1.4.1` should work.
